openapi: 3.0.1
info:
  title: 天气预报 API
  version: 1.0.0
  description: 使用您的 API KEY 获取实时天气数据。
servers:
  - url: https://api.example.com/v1  # 替换为实际 API 的根地址
paths:
  /weather/now:
    get:
      summary: 获取实时天气
      description: 根据城市 ID 返回实时天气数据。
      parameters:
        - name: location
          in: query
          required: true
          schema:
            type: string
            example: "101010100"
        - name: key
          in: query
          required: true
          schema:
            type: string
            example: "50df2f0ae9b240baaec000cbb37ae2fc"  # 替换为实际 API KEY
      responses:
        '200':
          description: 成功返回天气数据
          content:
            application/json:
              schema:
                type: object
                properties:
                  temp:
                    type: number
                    example: 25.0